version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:12.16-alpine3.18
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  db_data: